name = "floating-island"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-24"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "solian.app", zone_name = "solian.app", custom_domain = true }
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "FAILOVER_CHAT_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
preview_id = "REPLACE_WITH_KV_PREVIEW_ID"
