name = "floating-island"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-02-24"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "solian.app", zone_name = "solian.app", custom_domain = true },
]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "FAILOVER_CHAT_KV"
id = "238dc2babe874520baae86d7041ac244"
preview_id = "68ae7bc348c14d6c8105746b2b7f2c0c"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[placement]
region = "aws:ap-east-1"
