/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBtn: typeof import('naive-ui')['NBtn']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCardSection: typeof import('naive-ui')['NCardSection']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NChip: typeof import('naive-ui')['NChip']
    NCode: typeof import('naive-ui')['NCode']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialog: typeof import('naive-ui')['NDialog']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImg: typeof import('naive-ui')['NImg']
    NInfiniteScroll: typeof import('naive-ui')['NInfiniteScroll']
    NInput: typeof import('naive-ui')['NInput']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NTextarea: typeof import('naive-ui')['NTextarea']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const NAlert: typeof import('naive-ui')['NAlert']
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NBtn: typeof import('naive-ui')['NBtn']
  const NButton: typeof import('naive-ui')['NButton']
  const NCard: typeof import('naive-ui')['NCard']
  const NCardSection: typeof import('naive-ui')['NCardSection']
  const NCarousel: typeof import('naive-ui')['NCarousel']
  const NCarouselItem: typeof import('naive-ui')['NCarouselItem']
  const NChip: typeof import('naive-ui')['NChip']
  const NCode: typeof import('naive-ui')['NCode']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialog: typeof import('naive-ui')['NDialog']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NImage: typeof import('naive-ui')['NImage']
  const NImg: typeof import('naive-ui')['NImg']
  const NInfiniteScroll: typeof import('naive-ui')['NInfiniteScroll']
  const NInput: typeof import('naive-ui')['NInput']
  const NList: typeof import('naive-ui')['NList']
  const NListItem: typeof import('naive-ui')['NListItem']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NModal: typeof import('naive-ui')['NModal']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NProgress: typeof import('naive-ui')['NProgress']
  const NRadio: typeof import('naive-ui')['NRadio']
  const NRadioGroup: typeof import('naive-ui')['NRadioGroup']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSpace: typeof import('naive-ui')['NSpace']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NTag: typeof import('naive-ui')['NTag']
  const NTextarea: typeof import('naive-ui')['NTextarea']
  const NThemeEditor: typeof import('naive-ui')['NThemeEditor']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}